/*
 * Given a string containing of ‘0’, ‘1’ and ‘?’ wildcard characters, 
   generate all binary strings that can be formed by replacing each wildcard character by ‘0’ or ‘1’.

Input Format
The first line of input contains a single integer T denoting the number of test cases. Then T test cases follow. 
Each test case consist of two lines. The first line of each test case consists of a string S.

Constraints
1 ≤ T ≤ 60 1 ≤ length of string S ≤ 30

Output Format
Print all binary string that can be formed by replacing each wildcard character separated by space.

Sample Input
1
1??0?101
Sample Output
10000101 10001101 10100101 10101101 11000101 11001101 11100101 11101101
Explanation
For the Given test case, 10000101 can be generated by replacing wildcard character from 1??0?101 by 0s.
 */

package assignment6Recursion;
import java.util.*;

public class GenerateBinaryStrings {

	public static void main(String[] args) {
		Scanner sc = new Scanner(System.in);
		int t = sc.nextInt();
		while(t>=1 && t<=60) {
			String s = new String();
			s = sc.next();
			if(s.length()<=30) {
				StringBuilder sb = new StringBuilder();
				for(int i=0; i<s.length();i++) {
					sb.append(s.charAt(i));
						
				}
				calc(sb, 0);
				t=t-1;
				System.out.println();
				
			}
			
			
		}
		

	}
	
	public static void calc(StringBuilder str, int index) {
		if(index==str.length()) {
			System.out.print(str+" ");
			return;
		}
		if(str.charAt(index)=='?') {
			str.setCharAt(index, '0');
			calc(str, index+1);
			
			str.setCharAt(index, '1');
			calc(str, index+1);
			str.setCharAt(index, '?'); //backtrack
		}
		else {
			calc(str, index+1);
		}
	}

}
